CREATE OR REPLACE TABLE SALES(
ID INT,
CUSTOEMR_NAME STRING,
REGION STRING,
AMOUNT NUMBER(10,2),
SALE_DATE DATE
);
USE MY_PRACTICE_DB.MY_SCHEMA;


INSERT INTO SALES VALUES 
(1,'Aakash','West',5000.00,'2025-10-2'),
(2,'Gurumeeta','East',6000.00,'2025-10-3'),
(3,'Nikitha','North',7000.00,'2025-10-10'),
(4,'Shifana','South',8000.00,'2025-10-8'),
(5,'Varshini','West',9000.00,'2025-10-5');

SELECT * FROM SALES;


CREATE OR REPLACE VIEW SALES_VIEW AS
SELECT REGION ,SUM(AMOUNT) AS TOTAL_SALES ,COUNT(*) AS TOTAL_TRANSACTIONS
FROM SALES 
GROUP BY REGION;


SELECT * FROM SALES_VIEW;


CREATE OR REPLACE SECURE  VIEW SECURE_VIEW AS 
SELECT 
CUSTOEMR_NAME,
REGION,
CASE
    WHEN REGION='East' THEN '*****MASKED*****'
    ELSE TO_VARCHAR(AMOUNT)
END AS AMOUNT_DISPLAY
FROM SALES;

SELECT * FROM SECURE_VIEW;

CREATE OR REPLACE  MATERIALIZED VIEW MV_SALES_SUMMARY AS
SELECT
REGION,
SUM(AMOUNT) AS TOTAL_SALES,
COUNT(*) AS TXT_COUNT
FROM SALES
GROUP BY REGION;

SELECT * FROM MV_SALES_SUMMARY;

INSERT INTO SALES VALUES (6,'Vishal','North',6000.00,'2025-10-15')

SELECT * FROM MV_SALES_SUMMARY;