USE MY_PRACTICE_DB;

--PERMANENT TABLE
CREATE OR REPLACE TABLE orders ( orderid INT,orderdate date);

--TEMPORARY TABLE
CREATE OR REPLACE TEMPORARY TABLE temp_orders(
orderid INT,totalamount number(10,2));

--TRANSIENT TABLE 
CREATE OR REPLACE TRANSIENT TABLE staging_orders(
orderid int, orderstatus string
);

select * from MY_PRACTICE_DB.PUBLIC.STAGING_ORDERS;
SHOW TABLES IN SCHEMA MY_PRACTICE_DB.MY_SCHEMA;


ALTER TABLE orders
SET DATA_RETENTION_TIME_IN_DAYS = 30;




-- Create 3 table types

CREATE OR REPLACE TABLE sales_data(
saleid int,
amount number(10,2)
);

CREATE OR REPLACE TRANSIENT TABLE sales_stage (
saleid int,
region string
);

CREATE OR REPLACE TEMPORARY TABLE sales_temp(
saleid int,
discount number(5,2)
);

show tables in schema MY_PRACTICE_DB.MY_SCHEMA;

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA MY_PRACTICE_DB.MY_SCHEMA;

-- 1) Permanent table (default type)
CREATE OR REPLACE TABLE PERMANENT_TABLE (
  id  INT,
  name STRING
);

-- Permanent tables can have up to 90 days 
ALTER TABLE PERMANENT_TABLE
  SET DATA_RETENTION_TIME_IN_DAYS = 3;

-- 2) Transient table
CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE (
  ID   INT,
  NAME STRING
);

-- Max retention for TRANSIENT is 1 day (2 would fail)
ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS=1;

-- 3) Temporary table (session-scoped)
CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE (
  id  INT,
  name STRING
);

-- Verify types and retention
SHOW TABLES IN SCHEMA MY_PRACTICE_DB.MY_SCHEMA;

ALTER TABLE MY_PRACTICE_DB.PUBLIC.SALES_DATA SET DATA_RETENTION_TIME_IN_DAYS =4;

INSERT INTO SALES_DATA VALUES (2,'8999.00');

SELECT * FROM SALES_DATA;
DROP TABLE MY_PRACTICE_DB.PUBLIC.SALES_DATA;

SELECT * FROM SALES_DATA;


--RESTORING THE DROPPED SALES DATA
UNDROP TABLE MY_PRACTICE_DB.PUBLIC.SALES_DATA;

SELECT * FROM SALES_DATA;
